package com.jiangda.cust.integration.transport.gener.jdintegration;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-04T19:56:13.737+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "JDIntegrationServiceService", 
                  wsdlLocation = "http://192.168.43.74:8080/services/jdIntegration?wsdl",
                  targetNamespace = "http://ws.integration.framework.jiangda.com/") 
public class JDIntegrationServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.integration.framework.jiangda.com/", "JDIntegrationServiceService");
    public final static QName JDIntegrationServicePort = new QName("http://ws.integration.framework.jiangda.com/", "JDIntegrationServicePort");
    static {
        URL url = null;
        String location = "";
        try {
        	ResourceBundle registry = ResourceBundle.getBundle("com.jiangda.cust.integration.transport.gener.jdintegration.jdintegration");
            //url = new URL("http://localhost:8081/services/jdIntegration?wsdl");
        	location = registry.getString("wsdlLocation");
        	url = new URL(location);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JDIntegrationServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", location);
        }
        WSDL_LOCATION = url;
    }

    public JDIntegrationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JDIntegrationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JDIntegrationServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns JDIntegrationService
     */
    @WebEndpoint(name = "JDIntegrationServicePort")
    public JDIntegrationService getJDIntegrationServicePort() {
        return super.getPort(JDIntegrationServicePort, JDIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JDIntegrationService
     */
    @WebEndpoint(name = "JDIntegrationServicePort")
    public JDIntegrationService getJDIntegrationServicePort(WebServiceFeature... features) {
        return super.getPort(JDIntegrationServicePort, JDIntegrationService.class, features);
    }

}
